package io.github.kaseyawolf2.horizonwright.core.safety.death;

/** Explicit effects which the client adapter must enact before proceeding. */
public enum DeathSafetyDirective {
    ENTER_CRITICAL_RESTRICTIONS,
    RELEASE_CRITICAL_RESTRICTIONS,
    FORCE_CHECKPOINT_ACTIVE_TASK,
    CANCEL_ALL_NAVIGATION_AND_PENDING_WORK,
    REVOKE_ALL_ACTION_LEASES,
    CLEAR_ALL_INPUT_AND_KEYBINDINGS,
    CLEAR_NAVIGATION_PRIVATE_INPUT,
    RELEASE_ALL_HELD_USE,
    INVALIDATE_ACTION_AND_CONTAINER_EPOCHS,
    ENGAGE_DEATH_LOCKDOWN,
    PERSIST_UNRESOLVED_DEATH,
    SEND_EXACTLY_ONE_RESPAWN,
    START_INTERACTION_DISABLED_RECOVERY_NAVIGATION,
    AUTHORIZE_EXACT_GRAVE_ACTIVATION,
    ENTER_MANUAL_HOLD,
    RELEASE_DEATH_LOCKDOWN,
    CLEAR_UNRESOLVED_DEATH
}
