package io.github.kaseyawolf2.horizonwright.core.safety.death;

/** Fail-closed reasons which require explicit operator resolution. */
public enum ManualHoldReason {
    PRE_DEATH_CONTEXT_UNAVAILABLE,
    PROFILE_MISMATCH,
    REPEATED_DEATH_DURING_RECOVERY,
    UNSAFE_RECOVERY_NAVIGATION,
    RECOVERY_NAVIGATION_FAILED,
    INVENTORY_CHANGED_DURING_RECOVERY,
    GRAVE_REGION_UNLOADED,
    GRAVE_EVIDENCE_UNAVAILABLE,
    GRAVE_MISSING,
    GRAVE_WRONG_OWNER,
    GRAVE_EMPTY,
    MULTIPLE_OWNED_GRAVES,
    GRAVE_CHANGED,
    GRAVE_OUTSIDE_DEATH_DIMENSION,
    INSUFFICIENT_INVENTORY_CAPACITY,
    NO_EMPTY_HOTBAR_HAND,
    PRE_DEATH_CONTENT_MISMATCH,
    PARTIAL_RECOVERY,
    RECOVERED_INVENTORY_MISMATCH
}
